[tool.poetry]
name = "aoc-2023"
version = "0.1.0"
description = ""
authors = ["billy4479 <giachi.ellero@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
